orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      image_name: nodejs1
    docker: # Each job requires specifying an executor
    # (either docker, macos, or machine), see
      - image: circleci/node:12
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

jobs:
    publishLatestToHub: 
      executor: docker-publisher
 
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker build -t gopuc365/$image_name:latest .
              docker push gopuc365/$image_name:latest

workflows:
  version: 2
  build-master:
    jobs:
       - publishLatestToHub
          
                
                 
             
    
       
      


    
           
   
    

    